- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks: 
  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: ansible-inventory-test-rg
      name: testvm10
      vm_size: Standard_D1
      admin_username: ansibleuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/daanish/.ssh/authorized_keys
          key_data: {{ lookup('env','$VM_PUB') }}
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest