- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    PUB: "{{ lookup('env','$VM_PUB') }}"
    PUB_PATH: "{{ lookup('env','$VM_PUB_PATH') }}"
  tasks: 
  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: ansible-inventory-test-rg
      name: testvm10
      vm_size: Standard_D1
      admin_username: ansibleuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: "{{PUB_PATH}}"
          key_data: "{{PUB}}"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest